**The Iris Dataset**

三種の異なるアイリス(Setosa, Versicolour, Virginica)の花びらとがくの長さと幅のデータセット

In [1]:
%matplotlib inline
from __future__ import division, print_function

In [2]:
from keras.layers import Activation, Dense
from keras.layers.normalization import BatchNormalization
from keras.models import Sequential
from keras.utils.np_utils import to_categorical
import numpy as np

from sklearn import datasets
from sklearn.metrics import classification_report, confusion_matrix

Using TensorFlow backend.


In [3]:
np.random.seed(0)

データを準備

In [4]:
iris = datasets.load_iris()
X = iris.data
labels = iris.target
type(X)

numpy.ndarray

データをいくつか表示してみる

In [5]:
random_indices = np.random.permutation(len(X))
print('X:', X[random_indices[:10]], 'labels:', labels[random_indices[:10]], sep='\n')
#print('X:', X[random_indices[:10]], 'labels:', labels[random_indices[:10]])

X:
[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]]
labels:
[2 1 0 2 0 2 0 1 1 1]


ラベルをone-hotベクトル（値がひとつだけ1で他が0のベクトル）に変換

In [6]:
Y = to_categorical(labels)

変換後の正解データをいくつか表示してみる

In [7]:
print(Y[random_indices[:10]])

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


訓練用とテスト用の添字を取得

In [8]:
random_indices = np.random.permutation(len(X))
train_indices = random_indices[:len(X)//2]
test_indices = random_indices[len(X)//2:]

訓練用とテスト用にデータをそれぞれ準備

In [9]:
X_train, X_test = X[train_indices], X[test_indices]
Y_train, Y_test = Y[train_indices], Y[test_indices]
labels_train, labels_test = labels[train_indices], labels[test_indices]

ロジスティック回帰

In [11]:
model = Sequential()
model.add(Dense(3, input_dim=4))
model.add(Activation('softmax'))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
history=model.fit(X_train, Y_train, nb_epoch=200, batch_size=128)#学習が終わるまで

/home/ec2-user/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/200
75/75 [==============================] - 0s 2ms/step - loss: 3.8254 - acc: 0.3600
Epoch 2/200
75/75 [==============================] - 0s 17us/step - loss: 3.8145 - acc: 0.3600
Epoch 3/200
75/75 [==============================] - 0s 15us/step - loss: 3.8000 - acc: 0.3600
Epoch 4/200
75/75 [==============================] - 0s 19us/step - loss: 3.7855 - acc: 0.3600
Epoch 5/200
75/75 [==============================] - 0s 22us/step - loss: 3.7710 - acc: 0.3600
Epoch 6/200
75/75 [==============================] - 0s 13us/step - loss: 3.7572 - acc: 0.3600
Epoch 7/200
75/75 [==============================] - 0s 16us/step - loss: 3.7429 - acc: 0.3600
Epoch 8/200
75/75 [==============================] - 0s 16us/step - loss: 3.7287 - acc: 0.3600
Epoch 9/200
75/75 [==============================] - 0s 16us/step - loss: 3.7147 - acc: 0.3600
Epoch 10/200
75/75 [==============================] - 0s 17us/step - loss: 3.7006 - acc: 0.3600
Epoch 11/200
75/75 [==============================

Epoch 87/200
75/75 [==============================] - 0s 13us/step - loss: 2.8038 - acc: 0.6400
Epoch 88/200
75/75 [==============================] - 0s 13us/step - loss: 2.7936 - acc: 0.6400
Epoch 89/200
75/75 [==============================] - 0s 13us/step - loss: 2.7835 - acc: 0.6400
Epoch 90/200
75/75 [==============================] - 0s 18us/step - loss: 2.7734 - acc: 0.6400
Epoch 91/200
75/75 [==============================] - 0s 17us/step - loss: 2.7633 - acc: 0.6400
Epoch 92/200
75/75 [==============================] - 0s 13us/step - loss: 2.7532 - acc: 0.6533
Epoch 93/200
75/75 [==============================] - 0s 13us/step - loss: 2.7432 - acc: 0.6533
Epoch 94/200
75/75 [==============================] - 0s 14us/step - loss: 2.7331 - acc: 0.6533
Epoch 95/200
75/75 [==============================] - 0s 15us/step - loss: 2.7231 - acc: 0.6533
Epoch 96/200
75/75 [==============================] - 0s 14us/step - loss: 2.7130 - acc: 0.6533
Epoch 97/200
75/75 [====================

Epoch 172/200
75/75 [==============================] - 0s 15us/step - loss: 1.9695 - acc: 0.6533
Epoch 173/200
75/75 [==============================] - 0s 16us/step - loss: 1.9599 - acc: 0.6533
Epoch 174/200
75/75 [==============================] - 0s 15us/step - loss: 1.9503 - acc: 0.6533
Epoch 175/200
75/75 [==============================] - 0s 16us/step - loss: 1.9407 - acc: 0.6533
Epoch 176/200
75/75 [==============================] - 0s 15us/step - loss: 1.9311 - acc: 0.6533
Epoch 177/200
75/75 [==============================] - 0s 14us/step - loss: 1.9216 - acc: 0.6533
Epoch 178/200
75/75 [==============================] - 0s 14us/step - loss: 1.9120 - acc: 0.6533
Epoch 179/200
75/75 [==============================] - 0s 13us/step - loss: 1.9024 - acc: 0.6533
Epoch 180/200
75/75 [==============================] - 0s 15us/step - loss: 1.8929 - acc: 0.6533
Epoch 181/200
75/75 [==============================] - 0s 14us/step - loss: 1.8833 - acc: 0.6533
Epoch 182/200
75/75 [=========

In [13]:
loss, acc = model.evaluate(X_test, Y_test, verbose=0)#戻り値として何を返しているのか？
print('accuracy: {:.2f}'.format(acc))
print(loss)

accuracy: 0.68
1.6266301091512043


In [14]:
labels_pred = model.predict_classes(X_test, verbose=0)
print(confusion_matrix(labels_test, labels_pred))
print(classification_report(labels_test, labels_pred))

[[28  0  0]
 [ 0  0 24]
 [ 0  0 23]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        28
          1       0.00      0.00      0.00        24
          2       0.49      1.00      0.66        23

avg / total       0.52      0.68      0.57        75



/home/ec2-user/.pyenv/versions/3.6.5/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


多層パーセプトロン

In [14]:
model = Sequential()
model.add(Dense(16, input_dim=4))#どうやって16を算出している？試行錯誤の結果?
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dense(16))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dense(3))
model.add(BatchNormalization())
model.add(Activation('softmax'))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [15]:
model.fit(X_train, Y_train, nb_epoch=200, batch_size=128)

/home/ec2-user/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/200
75/75 [==============================] - 1s 9ms/step - loss: 0.6994 - acc: 0.7733
Epoch 2/200
75/75 [==============================] - 0s 28us/step - loss: 0.6712 - acc: 0.7733
Epoch 3/200
75/75 [==============================] - 0s 36us/step - loss: 0.6454 - acc: 0.8133
Epoch 4/200
75/75 [==============================] - 0s 34us/step - loss: 0.6221 - acc: 0.8533
Epoch 5/200
75/75 [==============================] - 0s 28us/step - loss: 0.6013 - acc: 0.8667
Epoch 6/200
75/75 [==============================] - 0s 27us/step - loss: 0.5821 - acc: 0.8667
Epoch 7/200
75/75 [==============================] - 0s 27us/step - loss: 0.5644 - acc: 0.8667
Epoch 8/200
75/75 [==============================] - 0s 27us/step - loss: 0.5482 - acc: 0.8667
Epoch 9/200
75/75 [==============================] - 0s 29us/step - loss: 0.5331 - acc: 0.8667
Epoch 10/200
75/75 [==============================] - 0s 28us/step - loss: 0.5190 - acc: 0.8800
Epoch 11/200
75/75 [==============================

Epoch 87/200
75/75 [==============================] - 0s 27us/step - loss: 0.2428 - acc: 1.0000
Epoch 88/200
75/75 [==============================] - 0s 33us/step - loss: 0.2419 - acc: 1.0000
Epoch 89/200
75/75 [==============================] - 0s 41us/step - loss: 0.2410 - acc: 1.0000
Epoch 90/200
75/75 [==============================] - 0s 30us/step - loss: 0.2401 - acc: 1.0000
Epoch 91/200
75/75 [==============================] - 0s 26us/step - loss: 0.2393 - acc: 1.0000
Epoch 92/200
75/75 [==============================] - 0s 27us/step - loss: 0.2384 - acc: 1.0000
Epoch 93/200
75/75 [==============================] - 0s 26us/step - loss: 0.2376 - acc: 1.0000
Epoch 94/200
75/75 [==============================] - 0s 26us/step - loss: 0.2367 - acc: 1.0000
Epoch 95/200
75/75 [==============================] - 0s 27us/step - loss: 0.2359 - acc: 1.0000
Epoch 96/200
75/75 [==============================] - 0s 29us/step - loss: 0.2351 - acc: 1.0000
Epoch 97/200
75/75 [====================

Epoch 172/200
75/75 [==============================] - 0s 29us/step - loss: 0.1910 - acc: 1.0000
Epoch 173/200
75/75 [==============================] - 0s 33us/step - loss: 0.1906 - acc: 1.0000
Epoch 174/200
75/75 [==============================] - 0s 28us/step - loss: 0.1902 - acc: 1.0000
Epoch 175/200
75/75 [==============================] - 0s 29us/step - loss: 0.1897 - acc: 1.0000
Epoch 176/200
75/75 [==============================] - 0s 26us/step - loss: 0.1893 - acc: 1.0000
Epoch 177/200
75/75 [==============================] - 0s 28us/step - loss: 0.1889 - acc: 1.0000
Epoch 178/200
75/75 [==============================] - 0s 27us/step - loss: 0.1885 - acc: 1.0000
Epoch 179/200
75/75 [==============================] - 0s 27us/step - loss: 0.1880 - acc: 1.0000
Epoch 180/200
75/75 [==============================] - 0s 29us/step - loss: 0.1876 - acc: 1.0000
Epoch 181/200
75/75 [==============================] - 0s 34us/step - loss: 0.1872 - acc: 1.0000
Epoch 182/200
75/75 [=========

In [16]:
_, acc = model.evaluate(X_test, Y_test, verbose=0)
print('accuracy: {:.2f}'.format(acc))

accuracy: 0.92


In [17]:
labels_pred = model.predict_classes(X_test, verbose=0)
print(confusion_matrix(labels_test, labels_pred))
print(classification_report(labels_test, labels_pred))

[[28  0  0]
 [ 1 20  3]
 [ 0  2 21]]
             precision    recall  f1-score   support

          0       0.97      1.00      0.98        28
          1       0.91      0.83      0.87        24
          2       0.88      0.91      0.89        23

avg / total       0.92      0.92      0.92        75



In [18]:
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot

SVG(model_to_dot(model, show_shapes=True).create(prog='dot', format='svg'))

InvocationException: GraphViz's executables not found