In [1]:
% matplotlib inline
from __future__ import print_function

from collections import Counter
import json
import os
import codecs

import lda
import matplotlib.pyplot as plt
import numpy as np
import scipy.sparse as sparse
from sklearn.decomposition import LatentDirichletAllocation

In [13]:
#a = np.arange(12).reshape((3, 4))
b=np.arange(1,13).reshape(3,4)
print(b)
print(b[::-1][0:3])



#print(a)
#print(b)
#print(np.where(a==b))
#print(np.where(a==b)[0])
#print(np.where(a==b)[0][0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
